name: Host behavioral tests
on: [push, pull_request]
permissions:
  contents: read
jobs:
  sanitizers:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: apiesse/tpuart
          ref: fb2fc2ac9004a6b5e5419b68c891ddfb4d284512
          path: .test-deps/tpuart
      - run: cmake -S test -B build/host -DENABLE_SANITIZERS=ON -DCMAKE_CXX_COMPILER=clang++ -DTPUART_SOURCE_DIR="$PWD/.test-deps/tpuart"
      - run: cmake --build build/host -j2
      - run: ctest --test-dir build/host --output-on-failure
        env:
          ASAN_OPTIONS: detect_leaks=1
          UBSAN_OPTIONS: halt_on_error=1
